/*
Copyright (c) 2020 by Stevie. All Rights Reserved.
*/

import React from 'react';
import {Row,Col} from 'antd'
import { Container } from '../../libs/base/base-style'
import StepBar,{Stage} from './Components/StageBar'
import Procedures,{Status} from './Components/ProcedureBox'
import Popover from './Components/Popover'
import ProgessBar from './Components/ProgessBar'
import styled from 'styled-components'
import { map } from 'lodash';
import avatar_ico from '../../assets/common/avatar.png'
const Main = styled(Container)`

  padding:40px;

`


const Box = styled(Container)`
display:flex;
flex-direction:row;

justify-content:center;
`

const Item = styled(Container)`
min-width:800px;
display:flex;
flex-direction:row;
`

const Task = styled(Container)`
display:flex;
flex-direction:row;
flex-wrap:wrap;
`
const data = [
  {
    title:'阶段一：什么就是什么',
    phase:'阶段一',
    activate:Stage.Done,
    roles:[
      {
      name:'信息通信席',
      userId:'123333',
      procedure:[
        {
          title:'写不下就隐藏写不下就隐藏写不下就隐藏',
          status:Status.Done,
          id:1,
        },{
          title:'有东西',
          status:Status.Done,
          id:2,
          task:[
            {
              title:'事件地点任务1事件地点任务1事件地点任务1事件地点任务1事件地点任务1事件地点任务1事件地点任务1',
              id:0,
              selected:false
            },
            {
              title:'事件地点任务2',
              id:1,
              selected:false
            },
            {
              title:'事件地点任务',
              id:2,
              selected:true
            },
            {
              title:'事件地点任务',
              id:3,
              selected:true
            },
            {
              title:'事件地点任务',
              id:4,
              selected:false
            }
          ]
        },{
          title:'写不下就隐藏写不下就隐藏写不下就隐藏',
          status:Status.Done,
          id:3,
        },{
          title:'写不下就隐藏写不下就隐藏写不下就隐藏',
          status:Status.Done,
          id:4,
        }
      ]
    },{
    name:'指挥控制席',
    userId:'12333s3',
    procedure:[
      {
        title:'写不下就隐藏写不下就隐藏写不下就隐藏',
        status:Status.Done,
        id:1,
      },{
        title:'有东西',
        status:Status.Done,
        id:2,
        task:[
          {
            title:'事件地点任务1事件地点任务1事件地点任务1事件地点任务1事件地点任务1事件地点任务1事件地点任务1',
            id:0,
            selected:false
          },
          {
            title:'事件地点任务2',
            id:1,
            selected:false
          },
          {
            title:'事件地点任务',
            id:2,
            selected:true
          },
          {
            title:'事件地点任务',
            id:3,
            selected:true
          },
          {
            title:'事件地点任务',
            id:4,
            selected:false
          }
        ]
      },{
        title:'写不下就隐藏写不下就隐藏写不下就隐藏',
        status:Status.Done,
        id:3,
      },{
        title:'写不下就隐藏写不下就隐藏写不下就隐藏',
        status:Status.Done,
        id:4,
      }
    ]
  },{
  name:'指挥员',
  userId:'12333s3',
  procedure:[
    {
      title:'写不下就隐藏写不下就隐藏写不下就隐藏',
      status:Status.Done,
      id:1,
    },{
      title:'有东西',
      status:Status.Done,
      id:2,
      task:[
        {
          title:'事件地点任务1事件地点任务1事件地点任务1事件地点任务1事件地点任务1事件地点任务1事件地点任务1',
          id:0,
          selected:false
        },
        {
          title:'事件地点任务2',
          id:1,
          selected:false
        },
        {
          title:'事件地点任务',
          id:2,
          selected:true
        },
        {
          title:'事件地点任务',
          id:3,
          selected:true
        },
        {
          title:'事件地点任务',
          id:4,
          selected:false
        }
      ]
    },{
      title:'写不下就隐藏写不下就隐藏写不下就隐藏',
      status:Status.Done,
      id:3,
    },{
      title:'写不下就隐藏写不下就隐藏写不下就隐藏',
      status:Status.Done,
      id:4,
    }
  ]
},{
name:'值勤处长',
userId:'12333s3',
procedure:[
  {
    title:'写不下就隐藏写不下就隐藏写不下就隐藏',
    status:Status.Done,
    id:1,
    isCritical:false,
  },{
    title:'有东西',
    status:Status.Done,
    id:2,
    isCritical:true,
    task:[
      {
        title:'事件地点任务1事件地点任务1事件地点任务1事件地点任务1事件地点任务1事件地点任务1事件地点任务1',
        id:0,
        selected:false
      },
      {
        title:'事件地点任务2',
        id:1,
        selected:false
      },
      {
        title:'事件地点任务',
        id:2,
        selected:true
      },
      {
        title:'事件地点任务',
        id:3,
        selected:true
      },
      {
        title:'事件地点任务',
        id:4,
        selected:false
      }
    ]
  },{
    title:'写不下就隐藏写不下就隐藏写不下就隐藏',
    status:Status.Done,
    id:3,
    isCritical:false,
  },{
    title:'写不下就隐藏写不下就隐藏写不下就隐藏',
    status:Status.Done,
    id:4,
    isCritical:false,
  }
]
},{
name:'处突维稳席',
userId:'12333s3',
procedure:[
  {
    title:'写不下就隐藏写不下就隐藏写不下就隐藏',
    status:Status.Done,
    id:1,
    isCritical:false,
  },{
    title:'有东西',
    status:Status.Done,
    id:2,
    isCritical:false,
    task:[
      {
        title:'事件地点任务1事件地点任务1事件地点任务1事件地点任务1事件地点任务1事件地点任务1事件地点任务1',
        id:0,
        selected:false
      },
      {
        title:'事件地点任务2',
        id:1,
        selected:false
      },
      {
        title:'事件地点任务',
        id:2,
        selected:true
      },
      {
        title:'事件地点任务',
        id:3,
        selected:true
      },
      {
        title:'事件地点任务',
        id:4,
        selected:false
      }
    ]
  },{
    title:'写不下就隐藏写不下就隐藏写不下就隐藏',
    status:Status.Done,
    id:3,
    isCritical:true,
  },{
    title:'写不下就隐藏写不下就隐藏写不下就隐藏',
    status:Status.Done,
    id:4,
    isCritical:false,
  }
]
},{
name:'侦查情报席',
userId:'12333s3',
procedure:[
  {
    title:'写不下就隐藏写不下就隐藏写不下就隐藏',
    status:Status.Done,
    id:1,
    isCritical:true,
  },{
    title:'有东西',
    status:Status.Done,
    id:2,
    isCritical:false,
    task:[
      {
        title:'事件地点任务1事件地点任务1事件地点任务1事件地点任务1事件地点任务1事件地点任务1事件地点任务1',
        id:0,
        selected:false
      },
      {
        title:'事件地点任务2',
        id:1,
        selected:false
      },
      {
        title:'事件地点任务',
        id:2,
        selected:true
      },
      {
        title:'事件地点任务',
        id:3,
        selected:true
      },
      {
        title:'事件地点任务',
        id:4,
        selected:false
      }
    ]
  },{
    title:'写不下就隐藏写不下就隐藏写不下就隐藏',
    status:Status.Done,
    id:3,
    isCritical:false,
  },{
    title:'写不下就隐藏写不下就隐藏写不下就隐藏',
    status:Status.Done,
    id:4,
    isCritical:false,
  }
]
},{
name:'政治工作席',
userId:'12333s3',
procedure:[
  {
    title:'写不下就隐藏写不下就隐藏写不下就隐藏',
    status:Status.Done,
    id:1,
    isCritical:false,
  },{
    title:'有东西',
    status:Status.Done,
    id:2,
    isCritical:false,
    task:[
      {
        title:'事件地点任务1事件地点任务1事件地点任务1事件地点任务1事件地点任务1事件地点任务1事件地点任务1',
        id:0,
        selected:false
      },
      {
        title:'事件地点任务2',
        id:1,
        selected:false
      },
      {
        title:'事件地点任务',
        id:2,
        selected:true
      },
      {
        title:'事件地点任务',
        id:3,
        selected:true
      },
      {
        title:'事件地点任务',
        id:4,
        selected:false
      }
    ]
  },{
    title:'写不下就隐藏写不下就隐藏写不下就隐藏',
    status:Status.Done,
    id:3,
    isCritical:false,
  },{
    title:'写不下就隐藏写不下就隐藏写不下就隐藏',
    status:Status.Done,
    id:4,
    isCritical:true,
  }
]
},{
name:'后装计划席',
userId:'12333s3',
procedure:[
  {
    title:'写不下就隐藏写不下就隐藏写不下就隐藏',
    status:Status.Done,
    id:1,
    isCritical:false,
  },{
    title:'有东西',
    status:Status.Done,
    id:2,
    isCritical:false,
    task:[
      {
        title:'事件地点任务1事件地点任务1事件地点任务1事件地点任务1事件地点任务1事件地点任务1事件地点任务1',
        id:0,
        selected:false
      },
      {
        title:'事件地点任务2',
        id:1,
        selected:false
      },
      {
        title:'事件地点任务',
        id:2,
        selected:true
      },
      {
        title:'事件地点任务',
        id:3,
        selected:true
      },
      {
        title:'事件地点任务',
        id:4,
        selected:false
      }
    ]
  },{
    title:'写不下就隐藏写不下就隐藏写不下就隐藏',
    status:Status.Done,
    id:3,
    isCritical:false,
  },{
    title:'写不下就隐藏写不下就隐藏写不下就隐藏',
    status:Status.Done,
    id:4,
    isCritical:true,
  }
]
}
],
},
]
const ColWrapper = styled.div`
display:flex;
flex-direction:column;
`
const Img = styled.img`
width:49px;
`
export default () => {
  return (
    <Main>
      <Box>
      {
        data.map(step => {
          return <Item>
            {map(step.roles,item =>{
              return <ColWrapper>
                <Img src={avatar_ico}/>
              </ColWrapper>
            })}

            <ColWrapper>
              <StepBar {...step}/>
              <ProgessBar complete={'80%'} activated ={'10%'} unactived={"10%"}/>
              <Task>
              <Row gutter={[8,8]} style={{width:'100%'}}>
              {map(step.roles,item =>{


                // const completeCnt = item.task ? item.task.filter(selected => selected.selected === true).length:0
                // const state = completeCnt === 0?Status.Initial:completeCnt === item.task?.length ?Status.Done:Status.InProgress
                // return  <Col span={6}>{item.task ?
                //   <Popover current = {{id:item.id,phase:step.phase}} data = {item.task} onChange = {(e:any)=> console.log(e)}>
                //     <Procedures title={item.title} status = {state} pid={item.id} tally={`${completeCnt}/${item.task.length}`}/>
                //   </Popover>:<Procedures {...item} pid={item.id} tally={`0/0`}/>}
                // </Col>

              })}
              </Row>
              </Task>
            </ColWrapper>
          </Item>
        })
      }
      </Box>
    </Main>
  )

};
